name: Daily Scraper

# Trigger the workflow every 24 hours
on:
  schedule:
    - cron: "16 3 * * *" # Runs at midnight UTC daily

jobs:
  scrape-job:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the script
      - name: Run scraper
        run: python scraper.py
